# Generated by Django 2.1.1 on 2019-06-14 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('userId', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=30)),
                ('contactNo', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=60)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
